### ISSUE TITLE
스키마 란 무엇인가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/hello-react#1]
3.2.4.2 더 많은 propTypes 종류
shape({name: React.proptypes.string, age: React.PropTypes.number}): 주어진 스키마를 가진 객체

**Comment by rosd89** [comment]
데이터의 명세서 같은 걸로 생각하시면 됩니다.
여기는 무슨 데이터가 있고, 어떤 타입을 지니는 것인지에 대한 명세를 표현합니다.
