### ISSUE TITLE
defaultProps와 propTypes에 대해

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/hello-react#2]
3.2.4.2 더 많은 propTypes 종류

defultProps 는 기본 값 지정할 때, propTypes 는 필수, 타입(type)을 지정할 때 사용한다.

정도만 알고 있으면 되나요?

**Comment by rosd89** [comment]
네 부모에게서 props를 못 받아왔을 때를 정의하기 위해서 defultProps가 정의합니다.
propTypes는 부모에서 전달받을 데이터의 타입이 무엇인지를 정하게 됩니다.
