### ISSUE TITLE
props와 state에 대한 설명인데 무슨 말인지 이해가 안돼요.

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/hello-react#3]
3.4 정리

props는 부모 컴포넌트가 설정하고, state는 컴포넌트 자체적으로 지닌 값으로 컴포넌트 내부에서 값을 업데이트한다.
props를 사용한다고 해서 값이 무조건 고정적인 것은 아니다. 부모 컴포넌트의 state를 자식 컴포넌트의 props로 전달하고, 자식 컴포넌트에서 특정 이벤트가 발생할 때 부모 컴포넌트의 메서드를 호출하면 props도 유동적으로 사용할 수 있다.

**Comment by rosd89** [comment]
state: 컴포넌트가 관리하는 데이터
props: 부모 컴포넌트에서 전달받은 데이터

이정도로 해석하시면 됩니다.
